POST localhost:8001/files
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="mulan"
Content-Type: image/jpeg

< Black-Widow.jpg
###